### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by hzpc-joostk** [ekimekim/yaargh#1]
Hi @ekimekim 

Thank you for continuing the development of [`argh`](/neithere/argh). As I use `argh` very often in my scripts, I would like to help you.

I had the following idea https://github.com/neithere/argh/pull/137

**Comment by ekimekim** [comment]
Hi @hzpc-joostk, thanks! I'll take all the help I can get :smile: 

I plan on going through all open issues/PRs on the upstream repo when I have time, I'll grab that PR when I do.

**Comment by ZeldaZach** [comment]
Can't wait to see how this turns out!!

**Comment by neithere** [comment]
Thanks from the original author of Argh, too! :)

I'll try to revive Argh soon and it would be great if the projects could be merged at some point (although I like both names, hehe). 
No problem if they diverge to pursue different goals, but so far it seems that yaargh has been mostly improving argh and moving more or less in the same direction, so it could be a matter of backporting your changes. Also the pull request #14 is exploring something that has to be addressed in Argh ASAP too.

**Comment by ekimekim** [comment]
This project kinda fell by the wayside, but I'd love to help work on argh proper. The intent was always just to continue work in the same spirit as argh, so if the project is active again there's no need for this fork anymore.
